### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by peter279k** [rashid2538/php-htmldiff#23]
As title, this project has been inactive for about whiles.

And it also has the forked version of [caxy/php-htmldiff](https://github.com/caxy/php-htmldiff).

Should I need to migrate to this forked one?

**Comment by jschroed91** [comment]
Hi @peter279k - I’m one of the maintainers of the Caxy fork. This project (as far as I know) is more or less a direct port of the htmldiff libraries mentioned in the readme.

The Caxy fork has been modified quite a lot since we originally forked from this repository, you can read about the differences here: https://github.com/caxy/php-htmldiff/blob/master/doc/differences.rst

The forked version has had a lot of improvements in terms of accuracy and configuration, but with that comes some performance trade offs (though not too bad)

**Comment by peter279k** [comment]
Hi @jschroed91, thanks for your quick reply.

I think I can look at the forked version because the forked has improvements and maintained.

I close this issue now because I concern about the `php-htmldiff` forked version.

**Comment by rashid2538** [comment]
Hi @peter279k, sorry for the late reply.

I'm not able to keeping this repository up to date anymore so I'll suggest you too to choose a better version. The repository mentioned by you is a far improved version of what I've to offer in the repo :)

**Comment by peter279k** [comment]
Hi @rashid2538, thanks for your reply.

I suggest you can add the abandoned message and recommend people to use the forked version I mention if possible.

And it will be easy for developers to find the replaced repository.

Also, it can let this repository be under [archived mode](https://help.github.com/en/articles/archiving-a-github-repository).
